FROM node:20-alpine AS builder
WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

FROM node:20-alpine
WORKDIR /app

COPY --from=builder /app /app

EXPOSE 8080

CMD ["node", "src/server.js"]

#docker buildx build --platform linux/amd64,linux/arm64 -t jzuletadev/mf-backend:latest .
#docker push jzuletadev/mf-backend:latest