FROM node:20-alpine AS builder
WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

FROM node:20-alpine
WORKDIR /app

COPY --from=builder /app /app

EXPOSE 8080

CMD ["node", "src/server.js"]

# docker build --platform=linux/arm64 -t jzuletadev/mf-backend:arm64 --push .
# docker build --platform=linux/amd64 -t jzuletadev/mf-backend:amd64 --push .